const STORAGE = {settings:'chekonam-settings', appearance:'chekonam-appearance', custom:'chekonam-custom', stats:'chekonam-stats', last:'chekonam-last', excluded:'chekonam-excluded', language:'chekonam-language'};
const fallbackManifest = {app:{name:'چه کنم؟',defaultCategory:'food',maxCustomOptions:12,catalog:'data/catalog.json'},categories:[]};
const fallbackData = {title:'انتخاب امروز',items:[{title:'یک گزینه‌ی تازه امتحان کن',description:'تصمیم را کوچک بگیر و همین حالا شروع کن.'},{title:'کمی صبر کن',description:'گاهی بهترین پاسخ بعد از یک نفس عمیق می‌رسد.'}]};
const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const fa = value => new Intl.NumberFormat('fa-IR').format(value);
const numberFor = value => state.language === 'en' ? new Intl.NumberFormat('en-US').format(value) : fa(value);
const state = {manifest:null, catalog:[], catalogEn:[], datasets:{}, activeCategory:null, activeItems:[], activeCategoryId:null, isIdeaList:false, lastSelections:{}, excludedByCategory:{}, currentIndex:0, optionSearch:'', language:'fa', mode:'cards', cardsLocked:false, appearance:{theme:'neon',scheme:'dark',depth:'2d',accent:'#d8f36b',secondary:'#72d8d2',radius:18,colorsTouched:false}, settings:{effects:true,surprise:true}, stats:{visits:0,choices:0,custom:0,byDay:{}}};
const colors = ['#d8f36b','#72d8d2','#8d7dff','#ffab73','#ff8fa3','#9fe3ff','#c8bfff','#ffce73'];

async function loadJSON(path, fallback){
  try { const response = await fetch(path); if(!response.ok) throw new Error('data unavailable'); return await response.json(); }
  catch { return fallback; }
}

async function init(){
  state.manifest = await loadJSON('data.json', fallbackManifest);
  state.catalog = await loadJSON(state.manifest.app?.catalog || 'data/catalog.json', []);
  state.catalogEn = await loadJSON('data/catalog.en.json', []);
  state.language = localStorage.getItem(STORAGE.language) || 'fa';
  state.settings = {...state.settings, ...JSON.parse(localStorage.getItem(STORAGE.settings) || '{}')};
  state.appearance = {...state.appearance, ...JSON.parse(localStorage.getItem(STORAGE.appearance) || '{}')};
  state.lastSelections = JSON.parse(localStorage.getItem(STORAGE.last) || '{}');
  state.excludedByCategory = JSON.parse(localStorage.getItem(STORAGE.excluded) || '{}');
  state.stats = {...state.stats, ...JSON.parse(localStorage.getItem(STORAGE.stats) || '{}')};
  state.stats.byDay = state.stats.byDay || {};
  const custom = JSON.parse(localStorage.getItem(STORAGE.custom) || 'null');
  if(custom?.items?.length){ state.manifest.categories.push({...custom, custom:true, icon:'＋', color:'#d8f36b', description:'بوم ذخیره‌شده‌ی تو'}); state.datasets.custom = custom; }
  renderCategories(); bindEvents(); applyAppearance(); translateUI();
  if(window.matchMedia&&!state.systemMedia){state.systemMedia=window.matchMedia('(prefers-color-scheme:light)');state.systemMedia.addEventListener('change',()=>{if(state.appearance.scheme==='system')applyAppearance();});}
  updateAdmin(); track('visit');
}

function categoryData(category){
  if(category.custom) return category;
  const source = state.language === 'en' ? state.catalogEn : state.catalog;
  return source[category.index] || fallbackData;
}

function renderCategories(){
  const grid = $('#categoryGrid');
  grid.innerHTML = state.manifest.categories.map((category,index) => { const data=categoryData(category); const title=data.title||category.title; const description=state.language==='en'&&!category.custom ? `${data.items?.length||50} ideas to choose from` : (data.description||category.description); return `<button class="category-card" data-category="${category.id}" style="--card-color:${category.color};animation-delay:${index * 45}ms"><span class="category-icon">${category.icon}</span><span class="category-arrow">←</span><h3>${title}</h3><p>${description}</p></button>`; }).join('');
}

function bindEvents(){
  $('#categoryGrid').addEventListener('click', event => { const card=event.target.closest('[data-category]'); if(card) openCategory(card.dataset.category); });
  $('#closeDecision').addEventListener('click', closeDecision); $('#spinButton').addEventListener('click', runMode); $('#rerollButton').addEventListener('click', runMode);
  $('#modeSwitcher').addEventListener('click', event => { const button=event.target.closest('[data-mode]'); if(button) setMode(button.dataset.mode); });
  $('#surpriseButton').addEventListener('click', surprise); $('#howButton').addEventListener('click', () => $('#howSection').scrollIntoView({behavior:'smooth'}));
  $('#customForm').addEventListener('submit', saveCustom); $('#languageToggle').addEventListener('click', () => setLanguage(state.language==='fa'?'en':'fa'));
  $('#optionSearch').addEventListener('input', event => { state.optionSearch=event.target.value; renderOptionCards(); });
  $('#cardCount').addEventListener('input', event => { $('#cardCountValue').textContent=numberFor(Number(event.target.value)); if(state.mode==='cards'&&!state.cardsLocked)renderMysteryCards(); });
  $('#appearanceToggle').addEventListener('click', openAppearance); $('#closeAppearance').addEventListener('click', closeAppearance);
  $$('.theme-choice').forEach(button => button.addEventListener('click', () => { state.appearance.theme=button.dataset.theme; saveAppearance(); applyAppearance(); showToast(state.language==='en'?`${button.querySelector('strong').textContent} theme enabled`:`تم ${button.querySelector('strong').textContent} فعال شد`); }));
  $$('#schemeSwitcher button').forEach(button => button.addEventListener('click', () => { state.appearance.scheme=button.dataset.scheme; saveAppearance(); applyAppearance(); }));
  $$('#depthSwitcher button').forEach(button => button.addEventListener('click', () => { state.appearance.depth=button.dataset.depth; saveAppearance(); applyAppearance(); }));
  $('#accentColor').addEventListener('input', event => { state.appearance.accent=event.target.value; state.appearance.colorsTouched=true; saveAppearance(); applyAppearance(); });
  $('#secondaryColor').addEventListener('input', event => { state.appearance.secondary=event.target.value; state.appearance.colorsTouched=true; saveAppearance(); applyAppearance(); });
  $('#radiusControl').addEventListener('input', event => { state.appearance.radius=Number(event.target.value); saveAppearance(); applyAppearance(); });
  $('#resetAppearance').addEventListener('click', () => { state.appearance={theme:'neon',scheme:'dark',depth:'2d',accent:'#d8f36b',secondary:'#72d8d2',radius:18,colorsTouched:false}; saveAppearance(); applyAppearance(); showToast(state.language==='en'?'Appearance reset':'ظاهر به حالت اولیه برگشت'); });
  $('#adminToggle').addEventListener('click', openAdmin); $('#closeAdmin').addEventListener('click', closeAdmin); $('#drawerBackdrop').addEventListener('click', closeAdmin); $('#drawerBackdrop').addEventListener('click', closeAppearance);
  $$('[data-setting]').forEach(input => { input.checked=state.settings[input.dataset.setting]!==false; input.addEventListener('change', () => { state.settings[input.dataset.setting]=input.checked; saveSettings(); }); });
  $('#clearLocalData').addEventListener('click', clearLocalData);
}

function setLanguage(language){
  state.language=language; localStorage.setItem(STORAGE.language,language); state.datasets={custom:state.datasets.custom}; renderCategories(); translateUI();
  if(state.activeCategory) openCategory(state.activeCategoryId);
}

function translateUI(){
  const en=state.language==='en'; document.documentElement.lang=en?'en':'fa'; document.documentElement.dir=en?'ltr':'rtl';
  $('#languageToggle').innerHTML=en?'<span>فا</span><span>Language</span>':'<span>EN</span><span>زبان</span>';
  $('#surpriseButton').innerHTML=en?'Surprise me <span>↗</span>':'غافلگیرم کن <span>↗</span>'; $('#howButton').innerHTML=en?'How does it work? <span>↓</span>':'چطور کار می‌کند؟ <span>↓</span>';
  $('.hero .eyebrow').innerHTML=en?'<span class="pulse-dot"></span> Your personal decision playground':'<span class="pulse-dot"></span> بوم تصمیم‌گیری شخصی تو'; $('.hero h1').innerHTML=en?'Sometimes you only need<br /><em>to try one path.</em>':'گاهی فقط باید<br /><em>یک راه را امتحان کرد.</em>'; $('.hero-text').textContent=en?'Stuck between options? Pick a topic, take a breath, and let a little chance start the game.':'بین گزینه‌ها گیر کردی؟ موضوعت را انتخاب کن، یک نفس بکش و بگذار شانس، بازی را شروع کند.';
  $('.workspace-section .eyebrow').textContent=en?'01 / CHOOSE':'01 / انتخاب کن'; $('.workspace-section h2').textContent=en?'What answer are you looking for?':'دنبال چه جوابی هستی؟'; $('.section-note').textContent=en?'A fresh path every time':'هر بار یک مسیر تازه';
  $('.custom-copy .eyebrow').textContent=en?'BUILD YOUR OWN':'بوم خودت را بساز'; $('.custom-copy h2').textContent=en?'Add your own options.':'گزینه‌های خودت را وارد کن.'; $('.custom-copy p:last-child').textContent=en?'For personal decisions, create a topic and add your options. This list stays on this browser only.':'برای تصمیم‌های خیلی شخصی، یک موضوع بساز و گزینه‌هایت را داخلش بریز. این لیست فقط روی همین مرورگر ذخیره می‌شود.'; $('#customForm label:first-child').firstChild.textContent=en?'Topic name':'نام موضوع'; $('#customForm label:nth-child(2)').firstChild.textContent=en?'Options ':'گزینه‌ها '; $('.label-hint').textContent=en?'one option per line':'هر گزینه در یک خط'; $('#customTitle').placeholder=en?'e.g. Tonight’s movies':'مثلاً: فیلم‌های امشب'; $('#customOptions').placeholder=en?'Watch a film\nRead a book\nGo to bed early':'فیلم ببینم\nکتاب بخوانم\nزود بخوابم'; $('.secondary-button:not(.reset-appearance)').innerHTML=en?'Build my board <span>＋</span>':'ساختن بوم من <span>＋</span>';
  $('.how-section .eyebrow').textContent=en?'SIMPLE, PERSONAL, NO ACCOUNT':'ساده، شخصی، بدون حساب کاربری'; const how=[en?['Pick a topic','From food and dates to tiny decisions, choose one.']:['یک موضوع بردار','از غذا و قرار تا تصمیم‌های لحظه‌ای، یکی را انتخاب کن.'],en?['Choose a game','Try hidden cards, auto-pick, or the scratch card.']:['یک بازی انتخاب کن','کارت مخفی، انتخاب خودکار یا بخت‌آزمایی دستی را امتحان کن.'],en?['Make it yours','Your last choice and settings stay here, without sign-up.']:['نتیجه را مال خودت کن','آخرین انتخاب و تنظیماتت روی مرورگر ذخیره می‌شوند، بدون ثبت‌نام.']]; $$('.how-grid article').forEach((article,i)=>{article.querySelector('h3').textContent=how[i][0];article.querySelector('p').textContent=how[i][1];}); $('.footer span:first-child').textContent=en?'Made for life’s small decisions.':'ساخته شده برای تصمیم‌های کوچک زندگی.'; $('.footer span:last-child').textContent=en?'© 2026 Chekonam':'© ۱۴۰۵ چه کنم؟';
  translateAppearance(en); translateAdmin(en);
}

function translateAppearance(en){
  const modeLabels=en?{cards:'Hidden cards',auto:'Auto-pick',scratch:'Scratch card'}:{cards:'کارت‌های مخفی',auto:'انتخاب خودکار',scratch:'بخت‌آزمایی'}; $$('.mode-button').forEach(button=>button.querySelector('small').textContent=modeLabels[button.dataset.mode]);
  $('#appearanceToggle').innerHTML=en?'<span>✦</span><span>Style</span>':'<span>✦</span><span>ظاهر</span>'; $('#adminToggle').innerHTML=en?'<span>⌘</span><span>Stats</span>':'<span>⌘</span><span>مدیریت</span>'; $('#appearanceToggle').setAttribute('aria-label',en?'Open style settings':'باز کردن تنظیمات ظاهر'); $('#adminToggle').setAttribute('aria-label',en?'Open stats panel':'باز کردن پنل مدیریت');
  $('#closeDecision').setAttribute('aria-label',en?'Close':'بستن'); $('#modeSwitcher').setAttribute('aria-label',en?'How to choose':'روش انتخاب نتیجه'); $('.option-list-tools label').textContent=en?'Search options':'جست‌وجوی گزینه‌ها'; $('#optionSearch').placeholder=en?'Try cafe, film, or workout...':'مثلاً کافه، فیلم یا ورزش...'; $('.card-count-control label').textContent=en?'Cards':'تعداد کارت'; $('.mystery-stage>small').textContent=en?'The other cards lock after your choice. Tap Fresh cards to try again.':'بعد از انتخاب، کارت‌های دیگر قفل می‌شوند؛ برای انتخاب دوباره، کارت‌های تازه را بزن.'; $('.auto-stage small').textContent=en?'I will choose from the options still available.':'از بین گزینه‌هایی که هنوز خط نخورده‌اند یک انتخاب پیدا می‌کنم.'; $('.scratch-kicker').textContent=en?'One choice is hidden behind this cover':'پشت این پوشش یک انتخاب پنهان است'; $('.scratch-copy small').textContent=en?'Scratch with your finger':'با انگشت بکش و بخراش'; $('.scratch-hint').textContent=en?'Scratch me':'خراش بده'; $('.scratch-stage>small').textContent=en?'Clear the dark cover with your mouse or finger.':'پوشش تیره را با ماوس یا انگشت پاک کن.'; $('#rerollButton').textContent=en?'Start over':'شروع دوباره'; $('#resultCount').textContent=en?`${numberFor(state.stats.choices||0)} choices today`:`${numberFor(state.stats.choices||0)} انتخاب امروز`;
  $('.appearance-drawer .eyebrow').textContent=en?'STYLE STUDIO':'استودیو ظاهر'; $('.appearance-drawer h2').textContent=en?'Shape your playground':'حال‌وهوای بوم'; $('.appearance-intro').textContent=en?'Tune colors and form for yourself. Settings stay on this browser.':'رنگ و فرم را برای خودت تنظیم کن. تنظیمات روی همین مرورگر می‌ماند.'; $('#schemeSwitcher button[data-scheme="system"]').textContent=en?'System':'سیستم'; $('#schemeSwitcher button[data-scheme="light"]').textContent=en?'Light':'روشن'; $('#schemeSwitcher button[data-scheme="dark"]').textContent=en?'Dark':'تاریک'; $('#depthSwitcher button[data-depth="2d"]').textContent=en?'2D calm':'2D آرام'; $('#depthSwitcher button[data-depth="3d"]').textContent=en?'3D depth':'3D عمقی'; const themes=en?[['neon','Neon','bright and playful'],['matte','Matte','quiet and deep'],['colorful','Colorful','happy and energetic'],['glass','Glass','clear and luxe'],['aurora','Aurora','our favorite']]:[['neon','نئونی','پرنور و بازیگوش'],['matte','مات','آرام و عمیق'],['colorful','رنگی','شاد و پرانرژی'],['glass','شیشه‌ای','شفاف و لوکس'],['aurora','شفق','انتخاب پیشنهادی']]; $$('.theme-choice').forEach((button,i)=>{button.querySelector('strong').textContent=themes[i][1];button.querySelector('small').textContent=themes[i][2];}); $$('.appearance-control strong')[0].textContent=en?'Accent color':'رنگ اصلی'; $$('.appearance-control small')[0].textContent=en?'Buttons and highlights':'برای دکمه‌ها و هایلایت‌ها'; $$('.appearance-control strong')[1].textContent=en?'Secondary color':'رنگ دوم'; $$('.appearance-control small')[1].textContent=en?'Effects and details':'برای افکت‌ها و جزئیات'; $('.radius-control strong').textContent=en?'Roundness everywhere':'گردی همه‌ی اجزا'; $('#resetAppearance').textContent=en?'Reset appearance':'بازنشانی ظاهر';
}

function translateAdmin(en){
  $('#adminDrawer .eyebrow').textContent=en?'CONTROL ROOM':'کنترل‌خانه'; $('#adminDrawer h2').textContent=en?'Stats panel':'پنل مدیریت'; $('.admin-note').textContent=en?'These stats are local to this browser. Real all-user analytics need a backend or analytics service.':'این آمار محلی است و فقط روی همین دستگاه ثبت می‌شود؛ برای آمار واقعی همه‌ی کاربران به بک‌اند یا سرویس تحلیل نیاز است.'; $('#adminDrawer .feature-controls h3').textContent=en?'Features':'قابلیت‌ها'; $$('.switch-row')[0].childNodes[0].textContent=en?'Visual effects ':'افکت‌های بصری '; $$('.switch-row')[1].childNodes[0].textContent=en?'Surprise suggestion ':'پیشنهاد غافلگیرکننده '; $('#clearLocalData').textContent=en?'Clear this browser data':'پاک کردن داده‌های این مرورگر'; $('.chart-heading h3').textContent=en?'Choices in the last 7 days':'انتخاب‌ها در ۷ روز اخیر';
}

async function openCategory(id){
  const category=state.manifest.categories.find(item=>item.id===id); if(!category)return;
  const cacheKey=`${state.language}:${id}`;
  if(!category.custom&&!state.datasets[cacheKey]) state.datasets[cacheKey]=category.file?await loadJSON(category.file,{...fallbackData,title:category.title}):categoryData(category);
  const data=category.custom?state.datasets.custom:(state.datasets[cacheKey]||categoryData(category)); state.activeCategory=category; state.activeItems=data.items||fallbackData.items; state.currentIndex=0; state.optionSearch=''; state.activeCategoryId=id; state.isIdeaList=category.id==='photo'||/ایده|عکاسی|idea|photo/i.test(data.title||category.title);
  $('#decisionEyebrow').textContent=data.title||category.title; $('#decisionTitle').textContent=category.custom?(state.language==='en'?'Your board':'بوم خودت'):(state.language==='en'?'Ready?':'آماده‌ای؟'); $('#decisionPanel').hidden=false; $('#decisionPanel').scrollIntoView({behavior:'smooth',block:'center'}); $('#optionSearch').value=''; $('#resultTitle').textContent=state.language==='en'?'Pick an option':'یک گزینه را انتخاب کن'; $('#resultDescription').textContent=state.language==='en'?'Choose a card count and tap one; the round locks after your choice.':'تعداد کارت‌ها را انتخاب کن و یکی را لمس کن؛ بعد از انتخاب، همان دور قفل می‌شود.'; $('#resultKicker').textContent=state.language==='en'?'Three hidden cards':'سه کارت ناشناس'; renderOptionCards(); setMode(state.mode); const previous=state.lastSelections[`${state.language}:${id}`]||state.lastSelections[id]; if(previous){$('#resultKicker').textContent=state.language==='en'?'Your last choice':'آخرین انتخاب تو';$('#resultTitle').textContent=previous.title;$('#resultDescription').textContent=previous.description||(state.language==='en'?'Saved from your last visit.':'این انتخاب از دفعه‌ی قبل حفظ شده است.');}
}

function closeDecision(){ $('#decisionPanel').hidden=true; state.activeCategory=null; }
function excludedIndexes(){ return new Set((state.excludedByCategory[state.activeCategoryId]||[]).map(Number)); }
function availableIndexes(){ const excluded=excludedIndexes(); return state.activeItems.map((_,index)=>index).filter(index=>!excluded.has(index)); }
function renderOptionCards(){
  const list=$('#optionCards'); if(!state.activeItems.length){list.innerHTML='';return;} const excluded=excludedIndexes(); const query=state.optionSearch.trim().toLocaleLowerCase(); const visible=state.activeItems.map((item,index)=>({item,index})).filter(({item,index})=>!excluded.has(index)&&(!query||`${item.title} ${item.description||''}`.toLocaleLowerCase().includes(query))); const hint=state.language==='en'?'Tick options to cross them out · up to 22 items':'برای خط‌زدن تیک بزن · حداکثر ۲۲ مورد'; const heading=state.language==='en'?'Option list':'لیست گزینه‌ها'; const empty=state.language==='en'?'Nothing left in this search.':'در این جست‌وجو گزینه‌ای باقی نمانده است.'; list.innerHTML=`<div class="list-heading"><span>${heading}</span><small>${hint}</small></div>${visible.length?visible.map(({item,index})=>`<button class="option-card" data-option-index="${index}" type="button"><span class="option-check">✓</span><span>${item.title}</span></button>`).join(''):`<p class="empty-options">${empty}</p>`}`; $('#excludedCount').textContent=state.language==='en'?`${numberFor(excluded.size)} crossed out`:`${numberFor(excluded.size)} خط‌خورده`; $$('#optionCards .option-card').forEach(card=>card.addEventListener('click',()=>markListOption(Number(card.dataset.optionIndex))));
}
function markListOption(index){ const excluded=excludedIndexes(); if(!excluded.has(index)&&excluded.size>=22)return showToast(state.language==='en'?'You can cross out up to 22 options':'برای این لیست حداکثر ۲۲ مورد را می‌توانی خط بزنی'); excluded.has(index)?excluded.delete(index):excluded.add(index); state.excludedByCategory[state.activeCategoryId]=[...excluded]; localStorage.setItem(STORAGE.excluded,JSON.stringify(state.excludedByCategory)); renderOptionCards(); }

function setMode(mode){
  state.mode=['cards','auto','scratch'].includes(mode)?mode:'cards'; state.cardsLocked=false; $$('.mode-button').forEach(button=>button.classList.toggle('active',button.dataset.mode===state.mode)); const cards=state.mode==='cards',auto=state.mode==='auto',scratch=state.mode==='scratch'; $('#mysteryStage').hidden=!cards; $('#autoStage').hidden=!auto; $('#scratchStage').hidden=!scratch; $('#optionCards').hidden=false; const copy={cards:state.language==='en'?['Three hidden cards','Choose a card count and tap one. The rest lock after your choice.','Fresh cards ↻']:['سه کارت ناشناس','تعداد کارت‌ها را انتخاب کن و یکی را لمس کن؛ بعد از انتخاب، همان دور قفل می‌شود.','کارت‌های تازه ↻'],auto:state.language==='en'?['Auto-pick','I will find one idea from the options still available.','Find one ✦']:['انتخاب خودکار','از بین گزینه‌هایی که هنوز خط نخورده‌اند یک پیشنهاد پیدا می‌کنم.','پیدا کن ✦'],scratch:state.language==='en'?['Manual scratch','Scratch the cover with your finger or mouse to reveal one idea.','New card ⌁']:['بخت‌آزمایی دستی','پوشش را با انگشت یا ماوس پاک کن تا یک انتخاب نمایان شود.','کارت تازه ⌁']}[state.mode]; $('#resultKicker').textContent=copy[0]; $('#resultDescription').textContent=copy[1]; $('#spinButton').innerHTML=copy[2]; if(cards)renderMysteryCards(); if(auto)$('#autoStage strong').textContent=state.language==='en'?'Finding one idea...':'در حال پیدا کردن...'; if(scratch)renderScratchCard();
}
function runMode(){ if(state.mode==='cards')return renderMysteryCards(); if(state.mode==='auto')return autoPick(); return renderScratchCard(); }
function autoPick(){ const available=availableIndexes(); if(!available.length)return showToast(state.language==='en'?'Crossed-out options are excluded from the game.':'همه‌ی گزینه‌ها خط خورده‌اند و چیزی برای انتخاب نمانده است.'); if(state.autoTimer)return; let ticks=0; $('#spinButton').disabled=true; state.autoTimer=setInterval(()=>{const index=available[Math.floor(Math.random()*available.length)];$('#autoStage strong').textContent=state.activeItems[index].title;ticks++;if(ticks>=9){clearInterval(state.autoTimer);state.autoTimer=null;$('#spinButton').disabled=false;choose(index);}},100); }
function distinctIndexes(count){ const available=availableIndexes(), indexes=[]; while(indexes.length<Math.min(count,available.length)){const index=available[Math.floor(Math.random()*available.length)];if(!indexes.includes(index))indexes.push(index);} return indexes; }
function renderMysteryCards(){ const holder=$('#mysteryCards'), indexes=distinctIndexes(Number($('#cardCount').value||3)); state.cardsLocked=false; const count=Number($('#cardCount').value||3); $('#cardCountValue').textContent=numberFor(count); $('#cardCount').disabled=false; if(!indexes.length){holder.innerHTML=`<p class="empty-options">${state.language==='en'?'Crossed-out options are excluded from the game.':'همه‌ی گزینه‌ها خط خورده‌اند و چیزی برای انتخاب نمانده است.'}</p>`;return;} holder.innerHTML=indexes.map(index=>`<button class="mystery-card" data-mystery-index="${index}" type="button" aria-label="${state.language==='en'?'Hidden card':'کارت ناشناس'}"><span>✦</span></button>`).join(''); $$('#mysteryCards .mystery-card').forEach(card=>card.addEventListener('click',()=>{if(state.cardsLocked)return;state.cardsLocked=true;$$('#mysteryCards .mystery-card').forEach(other=>{other.disabled=true;other.classList.toggle('revealed',other===card);});$('#cardCount').disabled=true;choose(Number(card.dataset.mysteryIndex));})); }
function renderScratchCard(){ const available=availableIndexes(); if(!available.length)return showToast(state.language==='en'?'Crossed-out options are excluded from the game.':'همه‌ی گزینه‌ها خط خورده‌اند و چیزی برای انتخاب نمانده است.'); const card=$('#scratchCard'),canvas=$('#scratchCanvas'),ctx=canvas.getContext('2d'),index=available[Math.floor(Math.random()*available.length)]; state.scratchState={index,painting:false,locked:false,lastCheck:0}; $('#scratchRevealText').textContent=state.activeItems[index]?.title||'یک گزینه‌ی ناشناس'; card.classList.remove('revealed'); ctx.globalCompositeOperation='source-over'; const gradient=ctx.createLinearGradient(0,0,canvas.width,canvas.height);gradient.addColorStop(0,'#161d32');gradient.addColorStop(.45,'#4b5675');gradient.addColorStop(1,'#11172a');ctx.fillStyle=gradient;ctx.fillRect(0,0,canvas.width,canvas.height);for(let i=0;i<70;i++){ctx.fillStyle=`rgba(255,255,255,${.04+Math.random()*.08})`;ctx.beginPath();ctx.arc(Math.random()*canvas.width,Math.random()*canvas.height,Math.random()*2.5,0,Math.PI*2);ctx.fill();}ctx.fillStyle='rgba(216,243,107,.55)';ctx.font='700 17px Vazirmatn';ctx.textAlign='center';ctx.fillText(state.language==='en'?'Scratch to reveal':'برای کشف انتخاب بکش',canvas.width/2,canvas.height/2); const paint=(event)=>{if(!state.scratchState.painting||state.scratchState.locked)return;const rect=canvas.getBoundingClientRect(),scaleX=canvas.width/rect.width,scaleY=canvas.height/rect.height,x=(event.clientX-rect.left)*scaleX,y=(event.clientY-rect.top)*scaleY;ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(x,y,22*scaleX,0,Math.PI*2);ctx.fill();const now=performance.now();if(now-state.scratchState.lastCheck>130){state.scratchState.lastCheck=now;const pixels=ctx.getImageData(0,0,canvas.width,canvas.height).data;let transparent=0,total=0;for(let i=3;i<pixels.length;i+=32){total++;if(pixels[i]<35)transparent++;}const progress=transparent/total;card.style.setProperty('--scratch-progress',progress);if(progress>.55)revealScratchCard();}}; canvas.onpointerdown=event=>{state.scratchState.painting=true;canvas.setPointerCapture(event.pointerId);paint(event);};canvas.onpointermove=paint;canvas.onpointerup=event=>{state.scratchState.painting=false;canvas.releasePointerCapture?.(event.pointerId);};canvas.onpointercancel=()=>{state.scratchState.painting=false;}; }
function revealScratchCard(){if(!state.scratchState||state.scratchState.locked)return;state.scratchState.locked=true;$('#scratchCard').classList.add('revealed');setTimeout(()=>choose(state.scratchState.index),250);}

function choose(index){ if(!state.activeItems[index]||excludedIndexes().has(index))return; state.currentIndex=index; const item=state.activeItems[index]; $('#resultKicker').textContent=state.language==='en'?'Today’s pick':'پیشنهاد امروز'; $('#resultTitle').textContent=item.title; $('#resultDescription').textContent=item.description||(state.language==='en'?'Try it and see where the day leads.':'این انتخاب را امتحان کن و ببین امروز به کجا می‌رسد.'); state.lastSelections[`${state.language}:${state.activeCategoryId}`]={index,title:item.title,description:item.description}; localStorage.setItem(STORAGE.last,JSON.stringify(state.lastSelections)); track('choice'); $('#resultCount').textContent=state.language==='en'?`${numberFor(state.stats.choices)} choices today`:`${numberFor(state.stats.choices)} انتخاب امروز`; if(state.settings.effects)confetti(); }
async function surprise(){ if(state.settings.surprise===false)return showToast(state.language==='en'?'Surprise suggestion is off':'پیشنهاد غافلگیرکننده خاموش است'); const categories=state.manifest.categories.filter(item=>!item.custom); const chosen=categories[Math.floor(Math.random()*categories.length)]; await openCategory(chosen.id); setMode('auto'); setTimeout(autoPick,350); }
function saveCustom(event){ event.preventDefault(); const title=$('#customTitle').value.trim(),items=$('#customOptions').value.split('\n').map(item=>item.trim()).filter(Boolean).slice(0,state.manifest.app.maxCustomOptions||12); if(!title||items.length<2)return showToast(state.language==='en'?'Add at least two options':'حداقل دو گزینه وارد کن'); const custom={id:'custom',title,description:state.language==='en'?`${numberFor(items.length)} personal options`:`${numberFor(items.length)} گزینه‌ی شخصی`,icon:'＋',items:items.map(item=>({title:item,description:state.language==='en'?'Added by you.':'انتخاب ساخته‌شده توسط خودت.'}))}; localStorage.setItem(STORAGE.custom,JSON.stringify(custom)); state.datasets.custom=custom; const existing=state.manifest.categories.findIndex(item=>item.id==='custom'); if(existing>=0)state.manifest.categories[existing]={...custom,custom:true,color:'#d8f36b'};else state.manifest.categories.push({...custom,custom:true,color:'#d8f36b'}); renderCategories(); track('custom'); showToast(state.language==='en'?'Your board is saved':'بوم شخصی تو ذخیره شد'); event.target.reset(); openCategory('custom'); }
function saveSettings(){localStorage.setItem(STORAGE.settings,JSON.stringify(state.settings));} function saveAppearance(){localStorage.setItem(STORAGE.appearance,JSON.stringify(state.appearance));}
function applyAppearance(){ const scheme=state.appearance.scheme==='system'?(window.matchMedia&&window.matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'):state.appearance.scheme; const customColors=state.appearance.colorsTouched===true&&state.appearance.accent!=='#d8f36b'; const accent=scheme==='light'&&!customColors?'#2e766b':state.appearance.accent,secondary=scheme==='light'&&!customColors?'#b3653e':state.appearance.secondary; document.body.classList.remove('theme-neon','theme-matte','theme-colorful','theme-glass','theme-aurora','scheme-light','scheme-dark','depth-2d','depth-3d'); document.body.classList.add(`theme-${state.appearance.theme}`,`scheme-${scheme}`,`depth-${state.appearance.depth||'2d'}`); document.body.style.setProperty('--lime',accent);document.body.style.setProperty('--cyan',secondary);document.body.style.setProperty('--user-radius',`${state.appearance.radius}px`); $('#accentColor').value=customColors?state.appearance.accent:accent;$('#secondaryColor').value=customColors?state.appearance.secondary:secondary;$('#radiusControl').value=state.appearance.radius;$('#radiusValue').textContent=numberFor(state.appearance.radius);$$('.theme-choice').forEach(button=>button.classList.toggle('active',button.dataset.theme===state.appearance.theme));$$('#schemeSwitcher button').forEach(button=>button.classList.toggle('active',button.dataset.scheme===state.appearance.scheme));$$('#depthSwitcher button').forEach(button=>button.classList.toggle('active',button.dataset.depth===state.appearance.depth)); }
function openAppearance(){ $('#appearanceDrawer').classList.add('open');$('#drawerBackdrop').classList.add('open');$('#appearanceDrawer').setAttribute('aria-hidden','false'); } function closeAppearance(){ $('#appearanceDrawer').classList.remove('open');if(!$('#adminDrawer').classList.contains('open'))$('#drawerBackdrop').classList.remove('open');$('#appearanceDrawer').setAttribute('aria-hidden','true'); }
function track(type){ const today=new Date().toISOString().slice(0,10);state.stats.visits=state.stats.visits||0;state.stats.choices=state.stats.choices||0;state.stats.custom=state.stats.custom||0;if(type==='visit')state.stats.visits++;if(type==='choice'){state.stats.choices++;state.stats.byDay[today]=(state.stats.byDay[today]||0)+1;}if(type==='custom')state.stats.custom++;localStorage.setItem(STORAGE.stats,JSON.stringify(state.stats));updateAdmin(); }
function updateAdmin(){ const stats=$('#statsGrid');if(!stats)return; const labels=state.language==='en'?['Local views','Choices','Custom boards','Categories']:['بازدید محلی','انتخاب‌ها','بوم‌های شخصی','دسته‌ها'];stats.innerHTML=[[labels[0],state.stats.visits||0],[labels[1],state.stats.choices||0],[labels[2],state.stats.custom||0],[labels[3],state.manifest?.categories?.length||0]].map(([label,value])=>`<div class="stat-card"><small>${label}</small><strong>${numberFor(value)}</strong></div>`).join('');const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);days.push({day:state.language==='en'?['S','M','T','W','T','F','S'][d.getDay()]:['ی','د','س','چ','پ','ج','ش'][d.getDay()],value:state.stats.byDay?.[key]||0});}const max=Math.max(...days.map(item=>item.value),1);$('#miniChart').innerHTML=days.map(item=>`<span class="chart-bar" data-day="${item.day}" style="height:${Math.max(5,item.value/max*100)}%"></span>`).join('');$('#chartTotal').textContent=numberFor(days.reduce((sum,item)=>sum+item.value,0)); }
function openAdmin(){ $('#adminDrawer').classList.add('open');$('#drawerBackdrop').classList.add('open');$('#adminDrawer').setAttribute('aria-hidden','false');updateAdmin(); } function closeAdmin(){ $('#adminDrawer').classList.remove('open');$('#drawerBackdrop').classList.remove('open');$('#adminDrawer').setAttribute('aria-hidden','true'); }
function clearLocalData(){ if(!confirm(state.language==='en'?'Clear all choices, settings, and custom board?':'همه‌ی انتخاب‌ها، تنظیمات و بوم شخصی پاک شود؟'))return;Object.values(STORAGE).forEach(key=>localStorage.removeItem(key));location.reload(); }
function showToast(message){ const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2600); }
function confetti(){ const layer=$('#confettiLayer');layer.innerHTML='';for(let i=0;i<34;i++){const piece=document.createElement('i');piece.className='confetti';piece.style.left=`${Math.random()*100}%`;piece.style.background=colors[i%colors.length];piece.style.setProperty('--drift',`${(Math.random()-.5)*220}px`);piece.style.animationDelay=`${Math.random()*.25}s`;piece.style.transform=`rotate(${Math.random()*90}deg)`;layer.appendChild(piece);}setTimeout(()=>layer.innerHTML='',2200); }
init();
